# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Dayalan/Music/UCT-FPGA-Course-2022/dnair_project/dnair_project.srcs/sources_1/ip/rom_data_I/rom_data_I.xci
# IP: The module: 'rom_data_I' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Dayalan/Music/UCT-FPGA-Course-2022/dnair_project/dnair_project.gen/sources_1/ip/rom_data_I/rom_data_I_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_data_I'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/Dayalan/Music/UCT-FPGA-Course-2022/dnair_project/dnair_project.srcs/sources_1/ip/rom_data_I/rom_data_I.xci
# IP: The module: 'rom_data_I' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Dayalan/Music/UCT-FPGA-Course-2022/dnair_project/dnair_project.gen/sources_1/ip/rom_data_I/rom_data_I_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_data_I'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
